app = "vsr-ai-service"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
